# Generated by Django 3.2 on 2021-07-02 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentResidue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_start', models.DateTimeField()),
                ('time_set', models.DateTimeField()),
                ('reason', models.CharField(max_length=500, null=True)),
                ('is_successful', models.BooleanField(default=True)),
                ('time_finalized', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=500, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_residue', to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_residue', to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_start', models.DateTimeField()),
                ('time_set', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=500, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='accounts.patient')),
            ],
        ),
    ]
