# Generated by Django 3.2 on 2021-07-02 03:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='remark',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_finalized',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AppointmentResidue',
        ),
    ]
