# Generated by Django 3.2 on 2021-07-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20210702_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('CD', 'cancelled by doctor'), ('CP', 'cancelled by patient'), ('SS', 'successful'), ('AA', 'active'), ('NA', 'Not avaliable')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_finalized',
            field=models.DateTimeField(null=True),
        ),
    ]
