# Generated by Django 3.2 on 2021-06-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('D', 'Doctor'), ('P', 'Patient'), ('S', 'Superuser')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
