# Generated by Django 3.2 on 2021-06-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glocose',
            name='date',
            field=models.DateField(auto_now_add=True, default='1998-12-12'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(verbose_name='date joined'),
        ),
    ]
