# Generated by Django 3.2 on 2021-06-10 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210610_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='date',
            field=models.DateField(default='1998-10-12'),
            preserve_default=False,
        ),
    ]
