# Generated by Django 3.2 on 2021-06-02 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210601_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'LGBT'), ('N', 'Dont want to reveal')], max_length=2, null=True)),
                ('media', models.CharField(max_length=150, null=True)),
                ('type', models.CharField(choices=[('D', 'DOCTOR'), ('P', 'PATIENT'), ('A', 'AUTH_DOCT'), ('S', 'SUPERUSER')], max_length=1, null=True)),
                ('token', models.CharField(max_length=250, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(editable=False, null=True)),
                ('signature', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.person')),
                ('speciality', models.CharField(max_length=120, null=True)),
                ('appoinment_duration', models.IntegerField(null=True)),
                ('practice_started', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('lunch_start', models.TimeField(null=True)),
                ('lunch_end', models.TimeField(null=True)),
                ('break_start', models.TimeField(null=True)),
                ('break_end', models.TimeField(null=True)),
                ('is_vc_avalible', models.BooleanField(default=False)),
                ('call_active', models.BooleanField(default=False)),
                ('charge_per_app', models.FloatField(default=0)),
            ],
            bases=('accounts.person',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.person')),
                ('married', models.BooleanField(default=False, null=True)),
                ('occupation', models.CharField(max_length=50, null=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative')], max_length=3, null=True)),
                ('education', models.CharField(choices=[('PRE', '7th'), ('SSC', '10th'), ('HSC', '12th'), ('GRD', 'Graduate'), ('PG', 'Post Graduate'), ('DR', 'PHD'), ('N', 'Dont want to reveal')], max_length=3, null=True)),
                ('sleep_start', models.TimeField(null=True)),
                ('sleep_end', models.TimeField(null=True)),
            ],
            bases=('accounts.person',),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(default='+91', max_length=3)),
                ('phone_no', models.CharField(max_length=120, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='accounts.person')),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=120, null=True)),
                ('value', models.CharField(max_length=120, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other', to='accounts.person')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicin_schedule', to='accounts.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_address', models.CharField(max_length=120, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email', to='accounts.person')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('addr_locality', models.CharField(max_length=100, null=True)),
                ('addr_district', models.CharField(max_length=50, null=True)),
                ('addr_state', models.CharField(max_length=50, null=True)),
                ('addr_country', models.CharField(max_length=50, null=True)),
                ('addr_pincode', models.CharField(max_length=50, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='accounts.person')),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight', to='accounts.patient')),
            ],
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescreption', to='accounts.doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescreption', to='accounts.patient'),
        ),
        migrations.CreateModel(
            name='PastDiseases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('past_diseases', models.CharField(max_length=120, null=True)),
                ('discription', models.CharField(max_length=1000, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_diseases', to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, null=True)),
                ('other_info', models.CharField(max_length=120, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Height',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('height', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='height', to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Glocose',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pre_meal', models.FloatField(null=True)),
                ('post_meal', models.FloatField(null=True)),
                ('date', models.DateField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glocose', to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(default='+91', max_length=3)),
                ('phone_no', models.CharField(max_length=120)),
                ('relation', models.CharField(max_length=120, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact', to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Cholesterol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('HDL', models.FloatField(null=True)),
                ('LDL', models.FloatField(null=True)),
                ('date', models.DateField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cholesterol', to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='General Break', max_length=1000, null=True)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('reason', models.CharField(max_length=1000, null=True)),
                ('repeat', models.CharField(choices=[('D', 'Daily'), ('W', 'Weakly'), ('M', 'Monthly'), ('N', 'None')], max_length=1)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_off', to='accounts.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('systolic', models.FloatField(null=True)),
                ('diastolic', models.FloatField(null=True)),
                ('date', models.DateField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_pressure', to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_start', models.DateTimeField(null=True)),
                ('heading', models.CharField(max_length=50, null=True)),
                ('reason', models.CharField(max_length=500, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('allergies', models.CharField(max_length=120, null=True)),
                ('discription', models.CharField(max_length=1000, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Addictions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('addiction', models.CharField(max_length=120, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adictions', to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(null=True)),
                ('review', models.CharField(max_length=1000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='accounts.patient')),
            ],
            options={
                'unique_together': {('doctor', 'patient')},
            },
        ),
    ]
