# Generated by Django 3.2 on 2021-06-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210602_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='break_end',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='break_start',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='lunch_end',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='lunch_start',
        ),
        migrations.AddField(
            model_name='doctor',
            name='charge_per_vc',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='charge_per_app',
            field=models.FloatField(default=200),
        ),
    ]
