# Generated by Django 3.2 on 2021-06-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_weight_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
