# Generated by Django 3.2 on 2021-06-14 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='addictions',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='addictions',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addictions', to='accounts.patient'),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cholesterol',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='glocose',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='height',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.DateField(default='2018-12-12'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weight',
            name='date',
            field=models.DateField(),
        ),
    ]
