# Generated by Django 3.2 on 2021-06-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210614_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergies',
            old_name='discription',
            new_name='description',
        ),
    ]
