# Generated by Django 3.2 on 2021-06-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('D', 'Doctor'), ('P', 'Patient'), ('S', 'Superuser')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
