# Generated by Django 3.2 on 2021-06-15 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_discription_allergies_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='person',
            new_name='patient',
        ),
    ]
