# Generated by Django 3.2 on 2021-06-19 10:31

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_person_emergencycontact_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile',
            field=models.ImageField(default='default', upload_to=accounts.models.get_profile_name),
        ),
    ]
