# Generated by Django 3.2 on 2021-06-19 10:32

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_doctor_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile',
            field=models.ImageField(default='default_profile', upload_to=accounts.models.get_profile_name),
        ),
    ]
