# Generated by Django 3.2 on 2021-06-19 12:51

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_doctor_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fcm_token',
            field=models.CharField(default='fHqtU6TdSWWrj_n57D8yC5:APA91bFyPIty32EBDaANTr6-qmhqF896jImzNx7wVUzorH22gscDloi-SqMcRJ_x-P2DbVMiTiZ2qb64yNAjIiUTi5Q4aCCQt43Fv3YV4oNHlVogJzyYs5-bcEkIevJMxVkHMfawymoM', max_length=700),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile',
            field=models.ImageField(default='default_profile.jpg', upload_to=accounts.models.get_profile_name),
        ),
    ]
