# Generated by Django 3.2 on 2021-06-19 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210619_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Granted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asking_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_asking', to=settings.AUTH_USER_MODEL)),
                ('granting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_granting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
