# Generated by Django 3.2 on 2021-06-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_granted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.DeleteModel(
            name='MedicineDetails',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
