# Generated by Django 3.2 on 2021-06-21 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('signature', models.CharField(max_length=500, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescreption', to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescreption', to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('repeat', models.CharField(choices=[('D1', 'Daily Once'), ('D2', 'Daily Twice'), ('D3', 'Daily Trice'), ('W1', 'Weakly Once')], max_length=2)),
                ('is_pre_meal', models.BooleanField(default=False)),
                ('total_dose', models.IntegerField()),
                ('dose', models.CharField(max_length=500, verbose_name='Details about each medicine and Dose')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_details', to='prescription.prescription')),
            ],
        ),
    ]
